"""
Article data model and MongoDB collection schema.

Each article document maps to exactly one MongoDB document.
The schema is enforced via a JSON Schema validator at the collection level
so that MongoDB itself rejects documents that are structurally incorrect.

Field reference
---------------
_id   : ObjectId (auto-generated by MongoDB)
url   : str   — canonical URL of the article (unique index)
title : str   — headline / title
feed  : str   — publisher / RSS feed name (e.g. "BBC News")
type  : str   — content type (e.g. "news", "opinion", "analysis")
pub   : str   — publication date (ISO-8601 string, e.g. "2026-03-11T09:00:00Z")
ret   : str   — retrieval/scrape datetime (ISO-8601)
lang  : str   — BCP-47 language tag (e.g. "en", "es")
refs  : list  — list of URLs referenced/cited within the article
sum   : str   — short summary / lede paragraph
body  : str   — main article body (no boilerplate/nav)
text  : str   — full raw text of the page (body + any ancillary text)

Cleaning rank (only present in the raw collection)
----------------------------------------------------
rank  : int
  0 — complete document, all fields present
  1 — non-crucial fields missing (dates, summary, refs, …); may be fixable via URL
  2 — crucial fields missing; document should be discarded
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# JSON Schema validator registered on the MongoDB collection
# ---------------------------------------------------------------------------

ARTICLE_VALIDATOR: dict[str, Any] = {
    "$jsonSchema": {
        "bsonType": "object",
        "required": ["url", "title", "feed", "body"],
        "properties": {
            "url":   {"bsonType": "string", "description": "Canonical article URL"},
            "title": {"bsonType": "string", "description": "Article headline"},
            "feed":  {"bsonType": "string", "description": "Publisher / RSS feed name"},
            "type":  {"bsonType": ["string", "null"], "description": "Content type"},
            "pub":   {"bsonType": ["string", "null"], "description": "Publication date (ISO-8601)"},
            "ret":   {"bsonType": ["string", "null"], "description": "Retrieval datetime (ISO-8601)"},
            "lang":  {"bsonType": ["string", "null"], "description": "BCP-47 language tag"},
            "refs":  {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Cited/referenced URLs",
            },
            "sum":   {"bsonType": ["string", "null"], "description": "Short summary"},
            "body":  {"bsonType": "string", "description": "Main article body text"},
            "text":  {"bsonType": ["string", "null"], "description": "Full raw page text"},
            "rank":  {
                "bsonType": ["int", "null"],
                "enum": [0, 1, 2, None],
                "description": "Data-quality rank (0=complete, 1=minor gaps, 2=discard)",
            },
        },
    }
}

# ---------------------------------------------------------------------------
# Index definitions
# ---------------------------------------------------------------------------

RAW_INDEXES = [
    # Unique constraint: don't store the same URL twice
    {"keys": [("url", 1)], "options": {"unique": True, "name": "url_unique"}},
    # Quickly filter by quality rank during cleaning
    {"keys": [("rank", 1)], "options": {"name": "rank_idx"}},
    # Support feed-level queries
    {"keys": [("feed", 1)], "options": {"name": "feed_idx"}},
    # Sort / filter by publication date
    {"keys": [("pub", -1)], "options": {"name": "pub_date_idx"}},
]

CLEAN_INDEXES = [
    {"keys": [("url", 1)], "options": {"unique": True, "name": "url_unique"}},
    # Category / subcategory will be added once the classifier is integrated
    {"keys": [("feed", 1)], "options": {"name": "feed_idx"}},
    {"keys": [("pub", -1)], "options": {"name": "pub_date_idx"}},
    {"keys": [("lang", 1)], "options": {"name": "lang_idx"}},
]


NER_ARTICLE_VALIDATOR: dict[str, Any] = {
    "$jsonSchema": {
        "bsonType": "object",
        "required": ["url", "title", "feed", "body", "entities"],
        "properties": {
            "url":   {"bsonType": "string"},
            "title": {"bsonType": "string"},
            "feed":  {"bsonType": "string"},
            "body":  {"bsonType": "string"},
            "entities": {
                "bsonType": "array",
                "items": {
                    "bsonType": "object",
                    "required": ["text", "label", "start", "end"],
                    "properties": {
                        "text":  {"bsonType": "string"},
                        "label": {"bsonType": "string"},
                        "start": {"bsonType": "int"},
                        "end":   {"bsonType": "int"},
                    },
                },
            },
            "type":  {"bsonType": ["string", "null"]},
            "pub":   {"bsonType": ["string", "null"]},
            "ret":   {"bsonType": ["string", "null"]},
            "lang":  {"bsonType": ["string", "null"]},
            "sum":   {"bsonType": ["string", "null"]},
        },
    }
}

NER_INDEXES = [
    {"keys": [("url", 1)], "options": {"unique": True, "name": "url_unique"}},
    {"keys": [("feed", 1)], "options": {"name": "feed_idx"}},
    {"keys": [("pub", -1)], "options": {"name": "pub_date_idx"}},
]


def build_article_dict(
    *,
    url: str,
    title: str,
    feed: str,
    body: str,
    type_: str | None = None,
    pub: str | None = None,
    ret: str | None = None,
    lang: str | None = None,
    refs: list[str] | None = None,
    sum_: str | None = None,
    text: str | None = None,
    rank: int | None = None,
) -> dict[str, Any]:
    """Return a plain dict that matches the article schema."""
    return {
        "url":   url,
        "title": title,
        "feed":  feed,
        "type":  type_,
        "pub":   pub,
        "ret":   ret,
        "lang":  lang,
        "refs":  refs,
        "sum":   sum_,
        "body":  body,
        "text":  text,
        "rank":  rank,
    }
