"""
Article data model and MongoDB collection schema.

Each article document maps to exactly one MongoDB document.
The schema is enforced via a JSON Schema validator at the collection level
so that MongoDB itself rejects documents that are structurally incorrect.

Field reference
---------------
_id   : ObjectId (auto-generated by MongoDB)
url   : str   — canonical URL of the article (unique index)
title : str   — headline / title
feed  : str   — publisher / RSS feed name (e.g. "BBC News")
type  : str   — content type (e.g. "news", "opinion", "analysis")
pub   : str   — publication date (ISO-8601 string, e.g. "2026-03-11T09:00:00Z")
ret   : str   — retrieval/scrape datetime (ISO-8601)
lang  : str   — BCP-47 language tag (e.g. "en", "es")
refs  : list  — list of URLs referenced/cited within the article
sum   : str   — short summary / lede paragraph
body  : str   — main article body (no boilerplate/nav)
text  : str   — full raw text of the page (body + any ancillary text)

Cleaning rank (only present in the raw collection)
----------------------------------------------------
rank  : int
  0 — complete document, all fields present
  1 — non-crucial fields missing (dates, summary, refs, …); may be fixable via URL
  2 — crucial fields missing; document should be discarded
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# JSON Schema validator registered on the MongoDB collection
# ---------------------------------------------------------------------------

ARTICLE_VALIDATOR: dict[str, Any] = {
    "$jsonSchema": {
        "bsonType": "object",
        "required": ["url", "title", "feed", "body"],
        "properties": {
            "url":   {"bsonType": "string", "description": "Canonical article URL"},
            "title": {"bsonType": "string", "description": "Article headline"},
            "feed":  {"bsonType": "string", "description": "Publisher / RSS feed name"},
            "type":  {"bsonType": ["string", "null"], "description": "Content type"},
            "pub":   {"bsonType": ["string", "null"], "description": "Publication date (ISO-8601)"},
            "ret":   {"bsonType": ["string", "null"], "description": "Retrieval datetime (ISO-8601)"},
            "lang":  {"bsonType": ["string", "null"], "description": "BCP-47 language tag"},
            "refs":  {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Cited/referenced URLs",
            },
            "sum":   {"bsonType": ["string", "null"], "description": "Short summary"},
            "body":  {"bsonType": "string", "description": "Main article body text"},
            "text":  {"bsonType": ["string", "null"], "description": "Full raw page text"},
            "clean_text": {"bsonType": ["string", "null"], "description": "Normalized text for NLP"},
            "money_tags": {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Regex-extracted monetary expressions",
            },
            "percent_tags": {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Regex-extracted percentage expressions",
            },
            "datetime_tags": {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Regex-extracted date/time mentions",
            },
            "url_tags": {
                "bsonType": ["array", "null"],
                "items": {
                    "bsonType": "object",
                    "properties": {
                        "url": {"bsonType": "string"},
                        "domain": {"bsonType": "string"},
                        "tld": {"bsonType": "string"},
                        "path": {"bsonType": "string"},
                    },
                },
                "description": "Structured URL/domain tags",
            },
            "doc_stats": {
                "bsonType": ["object", "null"],
                "properties": {
                    "char_count": {"bsonType": "int"},
                    "token_count": {"bsonType": "int"},
                    "sentence_count": {"bsonType": "int"},
                    "paragraph_count": {"bsonType": "int"},
                },
                "description": "Document-level statistics",
            },
            "cleaning_flags": {
                "bsonType": ["object", "null"],
                "description": "Quality flags emitted by cleaning rules",
            },
            "signal_counts": {
                "bsonType": ["object", "null"],
                "description": "Precomputed counts for extracted signal families",
            },
            "rank_reasons": {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Why a specific rank was assigned",
            },
            "source_author": {"bsonType": ["string", "null"], "description": "Feed entry author"},
            "source_tags": {
                "bsonType": ["array", "null"],
                "items": {"bsonType": "string"},
                "description": "Feed entry tags",
            },
            "source_summary": {"bsonType": ["string", "null"], "description": "Feed entry summary"},
            "source_published": {
                "bsonType": ["string", "null"],
                "description": "Published timestamp from feed metadata",
            },
            "quarantined_at": {
                "bsonType": ["string", "null"],
                "description": "UTC time when an item was moved to quarantine",
            },
            "rank":  {
                "bsonType": ["int", "null"],
                "enum": [0, 1, 2, None],
                "description": "Data-quality rank (0=complete, 1=minor gaps, 2=discard)",
            },
        },
    }
}

# ---------------------------------------------------------------------------
# Index definitions
# ---------------------------------------------------------------------------

RAW_INDEXES = [
    # Unique constraint: don't store the same URL twice
    {"keys": [("url", 1)], "options": {"unique": True, "name": "url_unique"}},
    # Quickly filter by quality rank during cleaning
    {"keys": [("rank", 1)], "options": {"name": "rank_idx"}},
    # Support feed-level queries
    {"keys": [("feed", 1)], "options": {"name": "feed_idx"}},
    # Sort / filter by publication date
    {"keys": [("pub", -1)], "options": {"name": "pub_date_idx"}},
]

CLEAN_INDEXES = [
    {"keys": [("url", 1)], "options": {"unique": True, "name": "url_unique"}},
    # Category / subcategory will be added once the classifier is integrated
    {"keys": [("feed", 1)], "options": {"name": "feed_idx"}},
    {"keys": [("pub", -1)], "options": {"name": "pub_date_idx"}},
    {"keys": [("lang", 1)], "options": {"name": "lang_idx"}},
]


def build_article_dict(
    *,
    url: str,
    title: str,
    feed: str,
    body: str,
    type_: str | None = None,
    pub: str | None = None,
    ret: str | None = None,
    lang: str | None = None,
    refs: list[str] | None = None,
    sum_: str | None = None,
    text: str | None = None,
    clean_text: str | None = None,
    money_tags: list[str] | None = None,
    percent_tags: list[str] | None = None,
    datetime_tags: list[str] | None = None,
    url_tags: list[dict[str, str]] | None = None,
    doc_stats: dict[str, int] | None = None,
    cleaning_flags: dict[str, bool] | None = None,
    signal_counts: dict[str, int] | None = None,
    rank_reasons: list[str] | None = None,
    source_author: str | None = None,
    source_tags: list[str] | None = None,
    source_summary: str | None = None,
    source_published: str | None = None,
    quarantined_at: str | None = None,
    rank: int | None = None,
) -> dict[str, Any]:
    """Return a plain dict that matches the article schema."""
    return {
        "url":   url,
        "title": title,
        "feed":  feed,
        "type":  type_,
        "pub":   pub,
        "ret":   ret,
        "lang":  lang,
        "refs":  refs,
        "sum":   sum_,
        "body":  body,
        "text":  text,
        "clean_text": clean_text,
        "money_tags": money_tags,
        "percent_tags": percent_tags,
        "datetime_tags": datetime_tags,
        "url_tags": url_tags,
        "doc_stats": doc_stats,
        "cleaning_flags": cleaning_flags,
        "signal_counts": signal_counts,
        "rank_reasons": rank_reasons,
        "source_author": source_author,
        "source_tags": source_tags,
        "source_summary": source_summary,
        "source_published": source_published,
        "quarantined_at": quarantined_at,
        "rank":  rank,
    }
