name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  production-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      deploy_path: "~/nlp-project"
      environment: "production"
    secrets: inherit
